---
parameters:
    email.default.broadcaster: account@mydomain.com
    swaybundle.platformprovider: ""
    swaybundle.platformappkey: ""
    swaybundle.platformclient.cache.driver: "apcu"
    swaybundle.platformclient.cache.lifetimemultiplier: 2
    swaybundle.platformclient.cache.params: []