services:
#    sway.example:
#        class: SwayBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    swaykernelService:
        class: SwayBundle\Core\Kernel
        arguments: [ "%swaybundle.platformprovider%", "%swaybundle.platformappkey%", "%swaybundle.platformclient.cache.driver%", "%swaybundle.platformclient.cache.lifetimemultiplier%" ]
    swayuserService:
        class: SwayBundle\User\User
        arguments: [ "@swaykernelService" ]
    swayMailer:
        class: SwayBundle\Mail\Mailer
        arguments: [ "%email.default.broadcaster%" ]
