services:
#    sway.example:
#        class: SwayBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    swaykernelService:
        class: SwayBundle\Core\Kernel
        arguments: [ "%swayframework.runtime_path%", "%swayframework.bin_file%", "%swayframework.loadmode%", "%swayframework.appidentifier%", "%swayframework.pwd%", "%swayframework.crossdomainssession%"  ]     
    swayuserService:
        class: SwayBundle\User\User
        arguments: [ "%swayframework.swuser.releasecookiesaftersignin%" ]
    swayMailer:
        class: SwayBundle\Mail\Mailer
        arguments: [ "%email.default.broadcaster%" ]
